### PR TITLE
Update README.md - fix refresh access token

### PR DESCRIPTION
**Pull request by lanort**
replaced non existing function exchangeToken($accessToken);

### CODE REVIEW

**Comment by PixellUp** [comment]
@victory-sokolov @nordigen Is this package development active or should I create my own wrapper around Nordigen API?

**Comment by victory-sokolov** [comment]
@PixellUp Hello, yes package is active, do you have any particular issues?

**Comment by PixellUp** [comment]
Thanks for the quick response @victory-sokolov.

I was going to provide some code improvements over missing methods that are possible over curl requests but not with the package itself, however, seeing there are 3 pull requests that haven't been merged or commented on for months ahead made me question the development status of this package.

**Comment by victory-sokolov** [comment]
@PixellUp We will try review all of them and Merge them next week

**Pull request merged**
